name: shared_models
description: A collection of models shared between the dict_parser and the Flutter client.
version: 1.0.0

environment:
  sdk: ">=2.8.1 <3.0.0"

dependencies:
  equatable: 1.2.2
  meta: 1.2.2

dev_dependencies:
  effective_dart: 1.2.3
  pedantic: 1.9.0
