name: shared_models
description: A collection of models shared between the dict_parser and the Flutter client.
version: 1.0.0

environment:
  sdk: ">=2.8.1 <3.0.0"

dependencies:
  equatable: 1.2.2
  json_annotation: 3.0.1
  kana_kit: 1.0.3+3
  meta: 1.1.8

dev_dependencies:
  build_runner: 1.10.0
  effective_dart: 1.2.3
  json_serializable: 3.3.0
  pedantic: 1.9.0
