name: dict_parser
description: >
  A parser that converts an XML dictionary file
  to an easily parsable dictionary for the Shiritori client app.
version: 1.0.0

environment:
  sdk: ">=2.8.1 <3.0.0"

dependencies:
  shared_models:
    path: ../shared_models
  kana_kit: 1.0.3+3
  meta: 1.1.8
  sqlite3: 0.1.4
  xml: 4.2.0

dev_dependencies:
  effective_dart: 1.2.3
  pedantic: 1.9.0
