name: shiritori
description: The japanese game Shiritori.
version: 1.0.0

publish_to: "none"

environment:
  sdk: ">=2.7.0 <3.0.0"
  flutter: 1.20.0-7.2.pre

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  shared_models:
    path: ../shared_models
  animations: 1.1.1
  avatar_glow: 1.2.0
  equatable: 1.2.3
  flutter_svg: 0.18.0
  font_awesome_flutter: 8.8.1
  intl: 0.16.1
  kana_kit: 1.0.3+3
  meta: 1.1.8
  provider: 4.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  effective_dart: 1.2.3
  intl_translation: 0.17.10
  pedantic: 1.9.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/png/
    - assets/images/svg/
    - assets/dicts/
  fonts:
    - family: HurmeGeometricSans
      fonts:
        - asset: assets/fonts/HurmeGeometricSans/HurmeGeometricSans_Hairline.otf
          weight: 100
        - asset: assets/fonts/HurmeGeometricSans/HurmeGeometricSans_HairlineItalic.otf
          weight: 100
          style: italic
        - asset: assets/fonts/HurmeGeometricSans/HurmeGeometricSans_Thin.otf
          weight: 200
        - asset: assets/fonts/HurmeGeometricSans/HurmeGeometricSans_ThinItalic.otf
          weight: 200
          style: italic
        - asset: assets/fonts/HurmeGeometricSans/HurmeGeometricSans_Light.otf
          weight: 300
        - asset: assets/fonts/HurmeGeometricSans/HurmeGeometricSans_LightItalic.otf
          weight: 300
          style: italic
        - asset: assets/fonts/HurmeGeometricSans/HurmeGeometricSans.otf
          weight: 400
        - asset: assets/fonts/HurmeGeometricSans/HurmeGeometricSans_Italic.otf
          weight: 400
          style: italic
        - asset: assets/fonts/HurmeGeometricSans/HurmeGeometricSans_SemiBold.otf
          weight: 600
        - asset: assets/fonts/HurmeGeometricSans/HurmeGeometricSans_SemiBoldItalic.otf
          weight: 600
          style: italic
        - asset: assets/fonts/HurmeGeometricSans/HurmeGeometricSans_Bold.otf
          weight: 700
        - asset: assets/fonts/HurmeGeometricSans/HurmeGeometricSans_BoldItalic.otf
          weight: 700
          style: italic
        - asset: assets/fonts/HurmeGeometricSans/HurmeGeometricSans_Black.otf
          weight: 900
        - asset: assets/fonts/HurmeGeometricSans/HurmeGeometricSans_BlackItalic.otf
          weight: 900
          style: italic
